### ISSUE TITLE
owca crashes while parsing the result from mesos.

### ISSUE THREAD

**Issue by WangJialei-A** [intel/owca#24]
```
Traceback (most recent call last):
  File ".bootstrap/pex/pex.py", line 352, in execute
  File ".bootstrap/pex/pex.py", line 284, in _wrap_coverage
  File ".bootstrap/pex/pex.py", line 315, in _wrap_profiling
  File ".bootstrap/pex/pex.py", line 397, in _execute
  File ".bootstrap/pex/pex.py", line 495, in execute_entry
  File ".bootstrap/pex/pex.py", line 510, in execute_pkg_resources
  File "/root/.pex/install/owca-0.1.dev213+g69633f1.d20190107-py3-none-any.whl.772bfaf4d1d8d5ea3921f399d71390ea5d1bb83f/owca-0.1.dev213+g69633f1.d20190107-py3-none-any.whl/owca/main.py", line 115, in main
    runner.run()
  File "/root/.pex/install/owca-0.1.dev213+g69633f1.d20190107-py3-none-any.whl.772bfaf4d1d8d5ea3921f399d71390ea5d1bb83f/owca-0.1.dev213+g69633f1.d20190107-py3-none-any.whl/owca/logger.py", line 112, in __trace
    rv = func(*args, **kw)
  File "/root/.pex/install/owca-0.1.dev213+g69633f1.d20190107-py3-none-any.whl.772bfaf4d1d8d5ea3921f399d71390ea5d1bb83f/owca-0.1.dev213+g69633f1.d20190107-py3-none-any.whl/owca/runner.py", line 160, in run
    tasks = self.node.get_tasks()
  File "/root/.pex/install/owca-0.1.dev213+g69633f1.d20190107-py3-none-any.whl.772bfaf4d1d8d5ea3921f399d71390ea5d1bb83f/owca-0.1.dev213+g69633f1.d20190107-py3-none-any.whl/owca/mesos.py", line 108, in get_tasks
    statuses = launched_task['statuses']
KeyError: 'statuses'
```

**Comment by felidadae** [comment]
We will today add fix for this problem. We have already investigated it.

**Comment by felidadae** [comment]
PR fixing: https://github.com/intel/owca/pull/28
