### ISSUE TITLE
owca crashes while restarting the mesos tasks

### ISSUE THREAD

**Issue by WangJialei-A** [intel/owca#25]
```
Traceback (most recent call last):
  File ".bootstrap/pex/pex.py", line 352, in execute
  File ".bootstrap/pex/pex.py", line 284, in _wrap_coverage
  File ".bootstrap/pex/pex.py", line 315, in _wrap_profiling
  File ".bootstrap/pex/pex.py", line 397, in _execute
  File ".bootstrap/pex/pex.py", line 495, in execute_entry
  File ".bootstrap/pex/pex.py", line 510, in execute_pkg_resources
  File "/root/.pex/install/owca-0.1.dev213+g69633f1.d20190107-py3-none-any.whl.772bfaf4d1d8d5ea3921f399d71390ea5d1bb83f/owca-0.1.dev213+g69633f1.d20190107-py3-none-any.whl/owca/main.py", line 115, in main
    runner.run()
  File "/root/.pex/install/owca-0.1.dev213+g69633f1.d20190107-py3-none-any.whl.772bfaf4d1d8d5ea3921f399d71390ea5d1bb83f/owca-0.1.dev213+g69633f1.d20190107-py3-none-any.whl/owca/logger.py", line 112, in __trace
    rv = func(*args, **kw)
  File "/root/.pex/install/owca-0.1.dev213+g69633f1.d20190107-py3-none-any.whl.772bfaf4d1d8d5ea3921f399d71390ea5d1bb83f/owca-0.1.dev213+g69633f1.d20190107-py3-none-any.whl/owca/runner.py", line 188, in run
    task_measurements = container.get_measurements()
  File "/root/.pex/install/owca-0.1.dev213+g69633f1.d20190107-py3-none-any.whl.772bfaf4d1d8d5ea3921f399d71390ea5d1bb83f/owca-0.1.dev213+g69633f1.d20190107-py3-none-any.whl/owca/containers.py", line 56, in get_measurements
    self.cgroup.get_measurements(),
  File "/root/.pex/install/owca-0.1.dev213+g69633f1.d20190107-py3-none-any.whl.772bfaf4d1d8d5ea3921f399d71390ea5d1bb83f/owca-0.1.dev213+g69633f1.d20190107-py3-none-any.whl/owca/cgroups.py", line 39, in get_measurements
    with open(os.path.join(self.cgroup_fullpath, CPU_USAGE)) as \
FileNotFoundError: [Errno 2] No such file or directory: '/sys/fs/cgroup/cpu/mesos/882366b6-9e94-4cca-84aa-baf2276d230d/cpuacct.usage'
```

**Comment by felidadae** [comment]
We will today add fix for this problem. We have already investigated it.
It's very rare, it seems that it is a race condition.

**Comment by felidadae** [comment]
https://github.com/intel/owca/pull/27 fix this.
